name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build
        run: make build-cross
      - name: Build image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ckotzbauer/k8spolicy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          no_push: true
      - name: Container scan
        uses: azure/container-scan@v0
        with:
          image-name: ckotzbauer/k8spolicy
